#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

[[ -z ${JELLYFIN_CONFIG_DIR} ]]  && JELLYFIN_CONFIG_DIR="${CONFIG_DIR}"         && export JELLYFIN_CONFIG_DIR
[[ -z ${JELLYFIN_DATA_DIR} ]]    && JELLYFIN_DATA_DIR="${CONFIG_DIR}/data"      && export JELLYFIN_DATA_DIR
[[ -z ${JELLYFIN_LOG_DIR} ]]     && JELLYFIN_LOG_DIR="${CONFIG_DIR}/log"        && export JELLYFIN_LOG_DIR
[[ -z ${JELLYFIN_CACHE_DIR} ]]   && JELLYFIN_CACHE_DIR="${CONFIG_DIR}/cache"    && export JELLYFIN_CACHE_DIR
[[ -z ${JELLYFIN_WEB_DIR} ]]     && JELLYFIN_WEB_DIR="/usr/share/jellyfin/web"  && export JELLYFIN_WEB_DIR

exec s6-setuidgid hotio "/usr/bin/jellyfin" --ffmpeg="/usr/lib/jellyfin-ffmpeg/ffmpeg"
