#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
----------------------------------------------------------------------
"

log_inf "Taking ownership of [/usr/share/jellyfin/*]."
find "/usr/share/jellyfin" \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
