#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

JELLYFIN_CONFIG_DIR="${CONFIG_DIR}/app"   && export JELLYFIN_CONFIG_DIR
JELLYFIN_DATA_DIR="${APP_DIR}/app/data"   && export JELLYFIN_DATA_DIR
JELLYFIN_LOG_DIR="${APP_DIR}/app/log"     && export JELLYFIN_LOG_DIR
JELLYFIN_CACHE_DIR="${APP_DIR}/app/cache" && export JELLYFIN_CACHE_DIR

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

# shellcheck disable=SC2086
redirect_cmd exec s6-setuidgid hotio "/usr/bin/jellyfin" --ffmpeg="/usr/lib/jellyfin-ffmpeg/ffmpeg" ${ARGS}
