#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -d "${CONFIG_DIR}/app/data" ]]; then
    echo "Creating directory ${CONFIG_DIR}/app/data"
    mkdir "${CONFIG_DIR}/app/data"
    chown hotio:hotio "${CONFIG_DIR}/app/data"
fi

if [[ ! -d "${CONFIG_DIR}/app/log" ]]; then
    echo "Creating directory ${CONFIG_DIR}/app/log"
    mkdir "${CONFIG_DIR}/app/log"
    chown hotio:hotio "${CONFIG_DIR}/app/log"
fi

if [[ ! -d "${CONFIG_DIR}/app/cache" ]]; then
    echo "Creating directory ${CONFIG_DIR}/app/cache"
    mkdir "${CONFIG_DIR}/app/cache"
    chown hotio:hotio "${CONFIG_DIR}/app/cache"
fi
